// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rsvzmhefqpsomjpyhqul.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJzdnptaGVmcXBzb21qcHlocXVsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjI0NTUxNzIsImV4cCI6MjA3ODAzMTE3Mn0.DL9mzid-cLkg2TsYJn9EVLsQVV29xFNmQzIYobIH7kQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});